name: teacher_sos_app
description: Classroom Arcade - AI Gaming System for Learning.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.4.9
  flutter_tts: ^3.8.5
  speech_to_text: ^6.3.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.9
  google_ml_kit: ^0.18.0
  confetti: ^0.7.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true